### ISSUE TITLE
Not delivered. unexpected status code 429 (electron status: ok).

### ISSUE THREAD

**Issue by illgitthat** [mautrix/gvoice#4]
Receiving messages works. 

Sending messages I get this error:
`Not delivered. unexpected status code 429 (electron status: ok).`

Restarting the bridge temporarily solves this issue. I'm not sure exactly what's causing this, but submitting here for tracking purposes.

**Comment by tulir** [comment]
How long after startup does it fail?

**Comment by illgitthat** [comment]
I'll try and do some additional testing but it's difficult because I don't send via GV too often.

Most I can offer right now is somewhere > 1 hour < 24 hours.

**Comment by skug67** [comment]
I'm having a similar problem, but at all times including immediately after restarting the bridge and the error message is:

⚠️ Your message was not bridged: unexpected status code 429 (electron status: unavailable)]

Messages are being received....

**Comment by michaelphagen** [comment]
Same issue here, using the docker container of this bridge and all messages get that error. I see in the logs: "Electron not running, sending message without signature data"

**Comment by michaelphagen** [comment]
Still getting this error

**Comment by illgitthat** [comment]
Since this issue is closed probably makes sense to open a new issue with
any relevant details you can find.
